name: yesod-markdown
version: 0.12.6.5
synopsis: Tools for using markdown in a yesod application
description: >
  A subset of Pandoc functionality useful for markdown processing in yesod
  applications
category: Web, Yesod
author: Alexander Dunlap, Patrick Brisbin
maintainer: Patrick Brisbin <pbrisbin@gmail.com>
license: GPL-2
github: pbrisbin/yesod-markdown
homepage: http://github.com/pbrisbin/yesod-markdown
extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >=4.8.0 && <5
  - blaze-html >=0.5 && <0.10
  - text >=0.11 && <2.0

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - bytestring >=0.9 && <0.12
    - pandoc >=2.0 && <2.12
    - blaze-markup >=0.5 && <0.9
    - xss-sanitize >=0.3.1 && <0.4
    - directory < 1.4
    - yesod-core >=1.2 && <1.7
    - yesod-form >=1.3 && <1.7
    - shakespeare >=2.0 && <2.1
    - persistent >=0.9 && < 2.12

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded
    dependencies:
      - yesod-markdown
      - hspec
