---
name: yesod-markdown
version: '0.12.3'
synopsis: Tools for using markdown in a yesod application
description: >
  A subset of Pandoc functionality useful for markdown processing in yesod
  applications
category: Web, Yesod
author: Alexander Dunlap, Patrick Brisbin
maintainer: Patrick Brisbin <pbrisbin@gmail.com>
license: GPL-2
github: pbrisbin/yesod-markdown
homepage: http://github.com/pbrisbin/yesod-markdown
extra-source-files:
  - README.md

dependencies:
  - base >=4.8.0 && <5

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - text >=0.11 && <2.0
    - bytestring >=0.9 && <0.11
    - pandoc >=2.0 && <2.3
    - blaze-html >=0.5 && <0.10
    - blaze-markup >=0.5 && <0.9
    - xss-sanitize >=0.3.1 && <0.4
    - directory
    - yesod-core >=1.2 && <1.7
    - yesod-form >=1.3 && <1.7
    - shakespeare >=2.0 && <2.1
    - persistent >=0.9

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded
    dependencies:
      - yesod-markdown
      - hspec
      - blaze-html
      - text
