on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        stack-yaml:
          - stack.yaml
          - stack-lts-15.12.yaml
          - stack-lts-14.27.yaml
          - stack-lts-12.10.yaml
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: freckle/stack-cache-action@main
      with:
        stack-yaml: ${{ matrix.stack-yaml }}
    - uses: freckle/stack-action@main
      with:
        stack-yaml: ${{ matrix.stack-yaml }}
        weeder: false
